#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../PY/web-2/nodejs/node-v24.18.1-win-x64/node_modules/corepack/dist/yarn.js" "$@"
else
  exec node  "$basedir/../../../PY/web-2/nodejs/node-v24.18.1-win-x64/node_modules/corepack/dist/yarn.js" "$@"
fi
